Improving SBT API
Ipotrick/Daxa pull request #94
Opened 2024-09-05 18:27 UTC by Jaisiero

Hi guys. 

I want you to check out these changes.

SBT now is more complex but allows you to relate better betwen shader stages and shader groups and ask for any SBT configuration.

I added more features (which I've been working on for a few weeks) to the MPM sample.

Let me know if some changes are needed.

2024-11-18 23:18 UTC, GabeRundlett requested changes
Hi @Jaisiero I would like to understand why the create default sbt function now constructs multiple buffers, one for each "region". I would like to know why this is, and if it makes sense, why the create default sbt also returns a buffer

2024-11-18 23:33 UTC, Jaisiero commented
Hi Gabe!

The thing is that the ray tracing pipeline drivers need to be copied to a host buffer and passed as arguments to the vkCmdTraceRays call to link them to the pipeline itself. This is better explained in the following link:

![image](https://github.com/user-attachments/assets/7948d806-0255-4e66-9aef-177433c25b16)
[SBT handles](https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/#shaderbindingtable/handles)

This functionality is quite complex and this is the best way I could think of for the user to have all the group handlers at their disposal since they are ordered according to the following requirements:
![image](https://github.com/user-attachments/assets/6252f7c0-ae9a-47c5-ac1c-cbab410db5dc)

I'm sure you can expose all this logic to the user, but you have to take into account all these details, such as aligning the handlers to memory. If you can think of a better way to deal with this problem I'm open to improvements of course.

2024-11-18 23:47 UTC, GabeRundlett commented
This does not explain why there are multiple buffers. Also, the buffer that contains the shader handles absolutely should not be a host buffer as it currently is. Either way, though, there should only be a SINGLE buffer created, with the function just returning the single buffer and the strided device address regions.

Note: the API has this, where there is both a buffer output in the function signature, but also a buffer output within the entries struct which is also a result of the same function.
```cpp
typedef struct
{
    daxa_BufferId buffer;
    daxa_SpanToConst(daxa_GroupRegionInfo) group_regions;
} daxa_RayTracingShaderBindingTableEntries;

DAXA_EXPORT daxa_Result
daxa_ray_tracing_pipeline_create_sbt(
    daxa_RayTracingPipeline pipeline,
    daxa_RayTracingShaderBindingTableEntries * out_sbts, daxa_BufferId * out_buffer,
    daxa_BuildShaderBindingTableInfo const * info);
```

2024-11-18 23:51 UTC, GabeRundlett commented
this appears to be a copy+paste error and I would like you to completely review the changes you've made because it does not seem complete or tested.

It appears that the buffer is created twice with the same size (but computed completely differently)
```cpp
    // Allocate a buffer for storing the SBT.
    auto sbt_info = daxa_BufferInfo{
        .size = current_offset,
        .allocate_info = DAXA_MEMORY_FLAG_HOST_ACCESS_SEQUENTIAL_WRITE,
        .name = std::bit_cast<daxa_SmallString>(name_cstr),
    };
    // NOTE: it is responsibility of the user to destroy the buffer
    auto & sbt_buffer_id = *out_buffer;
    auto const create_buffer_result = daxa_dvc_create_buffer(device, &sbt_info, r_cast<daxa_BufferId *>(&sbt_buffer_id));

    /// LATER, in the same function...

    // Allocate a buffer for storing the SBT.
    auto sbt_handler_info = daxa_BufferInfo{
        .size = sbt_handle_size,
        .allocate_info = DAXA_MEMORY_FLAG_HOST_ACCESS_RANDOM,
        .name = std::bit_cast<daxa_SmallString>(name_handle_cstr),
    };
    
     auto handle_result = daxa_dvc_create_buffer(device, &sbt_handler_info, r_cast<daxa_BufferId *>(&out_entries->buffer));
```

2024-12-18 17:13 UTC, Jaisiero commented
Hi again @GabeRundlett,
I am gonna try to explain better and then I can improve the API, and then I can make it easier to work with. 

RT pipeline needs to keep alive at least two buffers to work properly:

1. for shader handlers.
2. for groups to push them into the SBT (this second buffer depends on the first one's handlers).

The problem that I see is that depending on your requested groups, you need a subset of handlers or maybe all of them. Thus, somethings can go wrong if user doesn't do the right thing. Image I split the logic in two:

1. You ask for shader handlers: handler buffer returned.
2. You request to build some groups from the provided handlers (previously requested): group handler buffer returned.

What if handlers doesn't match group needs? If you ask for groups which need handlers not provided to the function?

Therefore, there's another option that I came to my mind. Handlers live during ray tracing pipeline's life-cycle and user doesn't need to manage them at all. Then you can ask for as many set of group as you want.


There's also another option which is not implemented right now and it's compatible with all of them. User can be able to provide a buffer to copy groups into it and thus, you can "recycle" it for many set of groups.


If you can think of anything else, you can share it and we can discuss it. I really want to push this forward.

Thank you,
Jaime.

2025-06-11 09:39 UTC, closed without merging